server:
  port: 8001

# mybatis 配置
mybatis:
  type-aliases-package: fun.gengyun.springcloud.pojo
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

# spring 配置
spring:
  application:
    name: springcloud-provider-dept # eureka页面 Instances currently registered with Eureka [Application]
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db01?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: gy4335!@

# Eureka 配置
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: spring-cloud-provider-dept-8001 # eureka页面 Instances currently registered with Eureka [Status]
    prefer-ip-address: true # 显示服务真实ip

info:
  app.name: entry-springcloud
  company.name: gengyun
